// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/raft.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Log Entry structure
type LogEntry struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

// RequestVote RPC - Leader Election
type RequestVoteRequest struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          string   `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex         int64    `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm          int64    `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{1}
}

func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (m *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(m, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteRequest) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{2}
}

func (m *RequestVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResponse.Unmarshal(m, b)
}
func (m *RequestVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResponse.Marshal(b, m, deterministic)
}
func (m *RequestVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResponse.Merge(m, src)
}
func (m *RequestVoteResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResponse.Size(m)
}
func (m *RequestVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResponse proto.InternalMessageInfo

func (m *RequestVoteResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

// AppendEntries RPC - Log Replication & Heartbeat
type AppendEntriesRequest struct {
	Term                 int64       `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             string      `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex         int64       `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm          int64       `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries              []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         int64       `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{3}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MatchIndex           int64    `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{4}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResponse) GetMatchIndex() int64 {
	if m != nil {
		return m.MatchIndex
	}
	return 0
}

// Client Request for key-value operations
type ClientRequestMessage struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestMessage) Reset()         { *m = ClientRequestMessage{} }
func (m *ClientRequestMessage) String() string { return proto.CompactTextString(m) }
func (*ClientRequestMessage) ProtoMessage()    {}
func (*ClientRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{5}
}

func (m *ClientRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestMessage.Unmarshal(m, b)
}
func (m *ClientRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestMessage.Marshal(b, m, deterministic)
}
func (m *ClientRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestMessage.Merge(m, src)
}
func (m *ClientRequestMessage) XXX_Size() int {
	return xxx_messageInfo_ClientRequestMessage.Size(m)
}
func (m *ClientRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestMessage proto.InternalMessageInfo

func (m *ClientRequestMessage) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ClientRequestMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ClientRequestMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ClientRequestResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LeaderId             string   `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestResponse) Reset()         { *m = ClientRequestResponse{} }
func (m *ClientRequestResponse) String() string { return proto.CompactTextString(m) }
func (*ClientRequestResponse) ProtoMessage()    {}
func (*ClientRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{6}
}

func (m *ClientRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestResponse.Unmarshal(m, b)
}
func (m *ClientRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestResponse.Marshal(b, m, deterministic)
}
func (m *ClientRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestResponse.Merge(m, src)
}
func (m *ClientRequestResponse) XXX_Size() int {
	return xxx_messageInfo_ClientRequestResponse.Size(m)
}
func (m *ClientRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestResponse proto.InternalMessageInfo

func (m *ClientRequestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ClientRequestResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ClientRequestResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ClientRequestResponse) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

// Get Status for monitoring
type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{7}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CurrentTerm          int64    `protobuf:"varint,3,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	LeaderId             string   `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex          int64    `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied          int64    `protobuf:"varint,6,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LogLength            int64    `protobuf:"varint,7,opt,name=log_length,json=logLength,proto3" json:"log_length,omitempty"`
	Peers                []string `protobuf:"bytes,8,rep,name=peers,proto3" json:"peers,omitempty"`
	Partitioned          []string `protobuf:"bytes,9,rep,name=partitioned,proto3" json:"partitioned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{8}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GetStatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetStatusResponse) GetCurrentTerm() int64 {
	if m != nil {
		return m.CurrentTerm
	}
	return 0
}

func (m *GetStatusResponse) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *GetStatusResponse) GetCommitIndex() int64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *GetStatusResponse) GetLastApplied() int64 {
	if m != nil {
		return m.LastApplied
	}
	return 0
}

func (m *GetStatusResponse) GetLogLength() int64 {
	if m != nil {
		return m.LogLength
	}
	return 0
}

func (m *GetStatusResponse) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *GetStatusResponse) GetPartitioned() []string {
	if m != nil {
		return m.Partitioned
	}
	return nil
}

// Network Partition simulation
type PartitionRequest struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionRequest) Reset()         { *m = PartitionRequest{} }
func (m *PartitionRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionRequest) ProtoMessage()    {}
func (*PartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{9}
}

func (m *PartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionRequest.Unmarshal(m, b)
}
func (m *PartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionRequest.Marshal(b, m, deterministic)
}
func (m *PartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionRequest.Merge(m, src)
}
func (m *PartitionRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionRequest.Size(m)
}
func (m *PartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionRequest proto.InternalMessageInfo

func (m *PartitionRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type PartitionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionResponse) Reset()         { *m = PartitionResponse{} }
func (m *PartitionResponse) String() string { return proto.CompactTextString(m) }
func (*PartitionResponse) ProtoMessage()    {}
func (*PartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{10}
}

func (m *PartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionResponse.Unmarshal(m, b)
}
func (m *PartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionResponse.Marshal(b, m, deterministic)
}
func (m *PartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionResponse.Merge(m, src)
}
func (m *PartitionResponse) XXX_Size() int {
	return xxx_messageInfo_PartitionResponse.Size(m)
}
func (m *PartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionResponse proto.InternalMessageInfo

func (m *PartitionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PartitionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Heal network partition
type HealRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealRequest) Reset()         { *m = HealRequest{} }
func (m *HealRequest) String() string { return proto.CompactTextString(m) }
func (*HealRequest) ProtoMessage()    {}
func (*HealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{11}
}

func (m *HealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealRequest.Unmarshal(m, b)
}
func (m *HealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealRequest.Marshal(b, m, deterministic)
}
func (m *HealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealRequest.Merge(m, src)
}
func (m *HealRequest) XXX_Size() int {
	return xxx_messageInfo_HealRequest.Size(m)
}
func (m *HealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealRequest proto.InternalMessageInfo

type HealResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealResponse) Reset()         { *m = HealResponse{} }
func (m *HealResponse) String() string { return proto.CompactTextString(m) }
func (*HealResponse) ProtoMessage()    {}
func (*HealResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92464e1b0c6cfce1, []int{12}
}

func (m *HealResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealResponse.Unmarshal(m, b)
}
func (m *HealResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealResponse.Marshal(b, m, deterministic)
}
func (m *HealResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealResponse.Merge(m, src)
}
func (m *HealResponse) XXX_Size() int {
	return xxx_messageInfo_HealResponse.Size(m)
}
func (m *HealResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealResponse proto.InternalMessageInfo

func (m *HealResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *HealResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*ClientRequestMessage)(nil), "raft.ClientRequestMessage")
	proto.RegisterType((*ClientRequestResponse)(nil), "raft.ClientRequestResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "raft.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "raft.GetStatusResponse")
	proto.RegisterType((*PartitionRequest)(nil), "raft.PartitionRequest")
	proto.RegisterType((*PartitionResponse)(nil), "raft.PartitionResponse")
	proto.RegisterType((*HealRequest)(nil), "raft.HealRequest")
	proto.RegisterType((*HealResponse)(nil), "raft.HealResponse")
}

func init() {
	proto.RegisterFile("proto/raft.proto", fileDescriptor_92464e1b0c6cfce1)
}

var fileDescriptor_92464e1b0c6cfce1 = []byte{
	// 742 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x51, 0x4f, 0xdb, 0x48,
	0x10, 0x56, 0x48, 0x20, 0xf1, 0x98, 0xa0, 0xb0, 0x17, 0xc0, 0x17, 0x38, 0x5d, 0xf0, 0xdd, 0x43,
	0x5e, 0x80, 0x13, 0xf7, 0x7a, 0x2f, 0x80, 0x4e, 0x80, 0x94, 0x56, 0x95, 0x41, 0x7d, 0xa8, 0x2a,
	0x45, 0xdb, 0x78, 0x08, 0x56, 0x1d, 0xdb, 0xdd, 0xdd, 0x44, 0xa5, 0xbf, 0xa2, 0x2f, 0x7d, 0xee,
	0x5f, 0xeb, 0x4f, 0xa9, 0x76, 0x76, 0xed, 0xd8, 0x49, 0x4a, 0xa5, 0x3e, 0x65, 0xe7, 0xdb, 0x99,
	0xd9, 0x6f, 0xe6, 0x9b, 0x71, 0xa0, 0x93, 0x89, 0x54, 0xa5, 0x67, 0x82, 0x3f, 0xa8, 0x53, 0x3a,
	0xb2, 0x86, 0x3e, 0xfb, 0x2f, 0xa1, 0x35, 0x4c, 0x27, 0xff, 0x27, 0x4a, 0x3c, 0x31, 0x06, 0x0d,
	0x85, 0x62, 0xea, 0xd5, 0xfa, 0xb5, 0x41, 0x3d, 0xa0, 0x33, 0xeb, 0xc2, 0x66, 0x94, 0x84, 0xf8,
	0xd1, 0xdb, 0x20, 0xd0, 0x18, 0xcc, 0x83, 0xe6, 0x38, 0x9d, 0x4e, 0x79, 0x12, 0x7a, 0xf5, 0x7e,
	0x6d, 0xe0, 0x04, 0xb9, 0xe9, 0x7f, 0xa9, 0x01, 0x0b, 0xf0, 0xc3, 0x0c, 0xa5, 0x7a, 0x9d, 0x2a,
	0xb4, 0xc7, 0xb5, 0xa9, 0x8f, 0x61, 0x7b, 0xcc, 0x93, 0x30, 0x0a, 0xb9, 0xc2, 0x51, 0x14, 0xd2,
	0x0b, 0x4e, 0xe0, 0x16, 0xd8, 0x6d, 0xc8, 0xfe, 0x86, 0x9d, 0x98, 0x4b, 0x35, 0x8a, 0xd3, 0xc9,
	0xc8, 0xd0, 0xa8, 0x53, 0x82, 0x6d, 0x8d, 0x0e, 0xd3, 0xc9, 0x2d, 0xb1, 0xf1, 0xa1, 0x5d, 0x78,
	0xd1, 0x2b, 0x0d, 0x72, 0x72, 0xad, 0xd3, 0x3d, 0x8a, 0xa9, 0x3f, 0x84, 0xdf, 0x2a, 0xb4, 0x64,
	0x96, 0x26, 0x12, 0x7f, 0xc4, 0x6b, 0x9e, 0x2a, 0x1c, 0x4d, 0x04, 0x4f, 0x14, 0x1a, 0x5e, 0xad,
	0xc0, 0xd5, 0xd8, 0xb5, 0x81, 0xfc, 0x6f, 0x35, 0xe8, 0x5e, 0x64, 0x19, 0x26, 0xa1, 0xee, 0x5c,
	0x84, 0xf2, 0xb9, 0x3a, 0x0f, 0xc1, 0x89, 0x91, 0x87, 0x28, 0x16, 0x45, 0xb6, 0x0c, 0x60, 0x2a,
	0xcc, 0x04, 0xce, 0x57, 0x2b, 0xd4, 0x68, 0xb9, 0xc2, 0xc2, 0xab, 0x5c, 0xa1, 0x75, 0xd2, 0x15,
	0xb2, 0x01, 0x34, 0xd1, 0x90, 0xf1, 0x36, 0xfb, 0xf5, 0x81, 0x7b, 0xbe, 0x73, 0x4a, 0x6a, 0xe7,
	0xf2, 0x06, 0xf9, 0x35, 0xfb, 0x0b, 0xda, 0x96, 0x90, 0x56, 0x2d, 0x52, 0xde, 0x96, 0x6d, 0x2a,
	0x81, 0x57, 0x84, 0xf9, 0x0f, 0xb0, 0xb7, 0x54, 0xe1, 0x33, 0x2d, 0xf3, 0xa0, 0x29, 0x67, 0xe3,
	0x31, 0x4a, 0x69, 0xbb, 0x95, 0x9b, 0xec, 0x4f, 0x70, 0xa7, 0x5c, 0x8d, 0x1f, 0x2b, 0xc5, 0x01,
	0x41, 0x54, 0x9a, 0xff, 0x16, 0xba, 0x57, 0x71, 0x84, 0x89, 0xb2, 0x2d, 0x7c, 0x81, 0x52, 0xf2,
	0x09, 0xb2, 0x23, 0x70, 0xd2, 0x0c, 0x05, 0x57, 0x51, 0x9a, 0xd0, 0x5b, 0x4e, 0xb0, 0x00, 0x58,
	0x07, 0xea, 0xef, 0xf1, 0xc9, 0x76, 0x53, 0x1f, 0xf5, 0xa0, 0xce, 0x79, 0x3c, 0x43, 0x3b, 0x90,
	0xc6, 0xf0, 0x3f, 0xc1, 0x5e, 0x25, 0x7b, 0x51, 0x45, 0x89, 0x71, 0xad, 0xca, 0xb8, 0x48, 0xb4,
	0x51, 0x4a, 0xa4, 0x51, 0x14, 0x22, 0x15, 0x79, 0x7a, 0x32, 0xaa, 0xd2, 0x36, 0xaa, 0xd2, 0xfa,
	0x0c, 0x3a, 0xd7, 0xa8, 0xee, 0x14, 0x57, 0xb3, 0x7c, 0x3e, 0xfc, 0xaf, 0x1b, 0xb0, 0x5b, 0x02,
	0x2d, 0x99, 0x03, 0x68, 0x26, 0x69, 0x48, 0x4b, 0x60, 0x2a, 0xdd, 0xd2, 0xe6, 0x6d, 0xa8, 0x5f,
	0x95, 0x8a, 0xab, 0x82, 0x0b, 0x19, 0xb4, 0x38, 0x33, 0x21, 0x30, 0x51, 0x66, 0x18, 0x4c, 0x53,
	0x5d, 0x8b, 0xdd, 0xaf, 0xcc, 0xdc, 0x12, 0x31, 0x8a, 0x27, 0x91, 0xad, 0x28, 0x9b, 0x36, 0x9e,
	0x30, 0x33, 0x70, 0xc7, 0x40, 0x2b, 0x36, 0xe2, 0x59, 0x16, 0x47, 0x18, 0xda, 0x09, 0xa1, 0x8d,
	0xba, 0x30, 0x10, 0xfb, 0x03, 0x40, 0x8f, 0x63, 0x8c, 0xc9, 0x44, 0x3d, 0x7a, 0x4d, 0x72, 0x70,
	0xe2, 0x74, 0x32, 0x24, 0x40, 0x53, 0xcf, 0x10, 0x85, 0xf4, 0x5a, 0xfd, 0xba, 0xa6, 0x4e, 0x06,
	0xeb, 0x83, 0x9b, 0x71, 0xa1, 0x22, 0x2d, 0x22, 0x86, 0x9e, 0x43, 0x77, 0x65, 0xc8, 0xff, 0x07,
	0x3a, 0xaf, 0x72, 0x33, 0xdf, 0xaa, 0x23, 0x70, 0x78, 0x18, 0x0a, 0x94, 0x12, 0xb5, 0x5c, 0x3a,
	0x66, 0x01, 0xf8, 0xd7, 0xb0, 0x5b, 0x8a, 0xf8, 0xa9, 0xbe, 0x1e, 0x34, 0xa7, 0x66, 0xc6, 0x6c,
	0x57, 0x73, 0xd3, 0x6f, 0x83, 0x7b, 0x83, 0x3c, 0xce, 0xb5, 0xba, 0x84, 0x6d, 0x63, 0xfe, 0x7a,
	0xca, 0xf3, 0xcf, 0x75, 0x70, 0x03, 0xfe, 0xa0, 0xee, 0x50, 0xcc, 0xa3, 0x31, 0xb2, 0x4b, 0x70,
	0x4b, 0x9f, 0x21, 0xe6, 0x99, 0x15, 0x5d, 0xfd, 0x60, 0xf6, 0x7e, 0x5f, 0x73, 0x63, 0x79, 0xdc,
	0x40, 0xbb, 0xb2, 0x99, 0xac, 0x67, 0x7c, 0xd7, 0x7d, 0x90, 0x7a, 0x87, 0x6b, 0xef, 0x16, 0x99,
	0x2a, 0xdb, 0x91, 0x67, 0x5a, 0xb7, 0x90, 0x79, 0xa6, 0xf5, 0xeb, 0xf4, 0x1f, 0x38, 0xc5, 0x58,
	0xb3, 0x7d, 0xe3, 0xb9, 0x3c, 0xfc, 0xbd, 0x83, 0x15, 0x7c, 0x11, 0x5d, 0x28, 0x98, 0x47, 0x2f,
	0x0f, 0x41, 0x1e, 0xbd, 0x2a, 0xf5, 0x09, 0x34, 0xb4, 0x4e, 0x6c, 0xd7, 0x38, 0x94, 0x24, 0xec,
	0xb1, 0x32, 0x64, 0xdc, 0x2f, 0xf7, 0xdf, 0x74, 0x35, 0x78, 0x32, 0xd6, 0x56, 0x22, 0x67, 0xf2,
	0x8c, 0xfe, 0x0f, 0xdf, 0x6d, 0xd1, 0xcf, 0xbf, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x49, 0x3f,
	0x5e, 0x86, 0x2a, 0x07, 0x00, 0x00,
}
